export const data = [
  {
    id: 1,
    first_name: "Luz",
    last_name: "Kennefick",
    email: "lkennefick0@printfriendly.com",
    gender: "Female",
  },
  {
    id: 2,
    first_name: "Rossy",
    last_name: "Hegdonne",
    email: "rhegdonne1@blinklist.com",
    gender: "Male",
  },
  {
    id: 3,
    first_name: "Jaimie",
    last_name: "Gansbuhler",
    email: "jgansbuhler2@webmd.com",
    gender: "Female",
  },
  {
    id: 4,
    first_name: "Elijah",
    last_name: "Oboy",
    email: "eoboy3@hud.gov",
    gender: "Male",
  },
  {
    id: 5,
    first_name: "Engelbert",
    last_name: "Putson",
    email: "eputson4@angelfire.com",
    gender: "Male",
  },
  {
    id: 6,
    first_name: "Hamlin",
    last_name: "Gobolos",
    email: "hgobolos5@globo.com",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Shaine",
    last_name: "Burgis",
    email: "sburgis6@nytimes.com",
    gender: "Male",
  },
  {
    id: 8,
    first_name: "Kendal",
    last_name: "Deboy",
    email: "kdeboy7@squidoo.com",
    gender: "Male",
  },
  {
    id: 9,
    first_name: "Bria",
    last_name: "Piper",
    email: "bpiper8@seesaa.net",
    gender: "Female",
  },
  {
    id: 10,
    first_name: "Adina",
    last_name: "Ebbing",
    email: "aebbing9@sbwire.com",
    gender: "Female",
  },
];
